import { Celebrity, ProductType, Template } from './types'

export const CELEBRITIES: Celebrity[] = [
  {
    id: 'cr7',
    name: 'Cristiano Ronaldo',
    nameAr: 'كريستيانو رونالدو',
    industry: 'sports',
    verified: true,
    nationality: 'Portuguese',
    nationalityAr: 'برتغالي',
    languages: ['English', 'Portuguese', 'Spanish', 'Arabic'],
    tags: ['Football', 'Global Icon', 'Al-Nassr'],
    tagsAr: ['كرة القدم', 'أيقونة عالمية', 'النصر'],
    avatarColor: 'linear-gradient(135deg, #1a56db 0%, #0e9f6e 100%)',
    initials: 'CR',
    image: '/celebs/cr7.svg',
    priceRange: {
      'avatar-studio': { min: 4500, max: 9000 },
      'full-body': { min: 12000, max: 25000 },
      greeting: { min: 1200, max: 3500 },
    },
  },
  {
    id: 'salah',
    name: 'Mohamed Salah',
    nameAr: 'محمد صلاح',
    industry: 'sports',
    verified: true,
    nationality: 'Egyptian',
    nationalityAr: 'مصري',
    languages: ['Arabic', 'English'],
    tags: ['Football', 'Liverpool', 'Arab Icon'],
    tagsAr: ['كرة القدم', 'ليفربول', 'أيقونة عربية'],
    avatarColor: 'linear-gradient(135deg, #c62a47 0%, #ff6b35 100%)',
    initials: 'MS',
    image: '/celebs/salah.svg',
    priceRange: {
      'avatar-studio': { min: 3500, max: 7000 },
      'full-body': { min: 9000, max: 18000 },
      greeting: { min: 900, max: 2500 },
    },
  },
  {
    id: 'amr-diab',
    name: 'Amr Diab',
    nameAr: 'عمرو دياب',
    industry: 'music',
    verified: true,
    nationality: 'Egyptian',
    nationalityAr: 'مصري',
    languages: ['Arabic'],
    tags: ['Pop', 'Legend', 'Arabic Music'],
    tagsAr: ['بوب', 'أسطورة', 'موسيقى عربية'],
    avatarColor: 'linear-gradient(135deg, #f59e0b 0%, #d97706 100%)',
    initials: 'AD',
    image: '/celebs/amr-diab.svg',
    priceRange: {
      'avatar-studio': { min: 2000, max: 5000 },
      'full-body': { min: 6000, max: 14000 },
      greeting: { min: 600, max: 1800 },
    },
  },
  {
    id: 'nancy-ajram',
    name: 'Nancy Ajram',
    nameAr: 'نانسي عجرم',
    industry: 'music',
    verified: true,
    nationality: 'Lebanese',
    nationalityAr: 'لبنانية',
    languages: ['Arabic', 'English'],
    tags: ['Pop', 'Pan-Arab', 'TV Host'],
    tagsAr: ['بوب', 'عربي', 'مقدمة تلفزيون'],
    avatarColor: 'linear-gradient(135deg, #ec4899 0%, #a855f7 100%)',
    initials: 'NA',
    image: '/celebs/nancy-ajram.svg',
    priceRange: {
      'avatar-studio': { min: 1800, max: 4000 },
      'full-body': { min: 5000, max: 11000 },
      greeting: { min: 500, max: 1500 },
    },
  },
  {
    id: 'neymar',
    name: 'Neymar Jr.',
    nameAr: 'نيمار جونيور',
    industry: 'sports',
    verified: true,
    nationality: 'Brazilian',
    nationalityAr: 'برازيلي',
    languages: ['Portuguese', 'Spanish', 'English'],
    tags: ['Football', 'Al-Hilal', 'Global Star'],
    tagsAr: ['كرة القدم', 'الهلال', 'نجم عالمي'],
    avatarColor: 'linear-gradient(135deg, #fbbf24 0%, #10b981 100%)',
    initials: 'NJ',
    image: '/celebs/neymar.svg',
    priceRange: {
      'avatar-studio': { min: 4000, max: 8000 },
      'full-body': { min: 10000, max: 22000 },
      greeting: { min: 1000, max: 3000 },
    },
  },
  {
    id: 'mrbeast',
    name: 'MrBeast',
    nameAr: 'مستر بيست',
    industry: 'social-media',
    verified: true,
    nationality: 'American',
    nationalityAr: 'أمريكي',
    languages: ['English'],
    tags: ['YouTube', 'Philanthropy', 'Viral'],
    tagsAr: ['يوتيوب', 'خيري', 'فيروسي'],
    avatarColor: 'linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)',
    initials: 'MB',
    image: '/celebs/mrbeast.svg',
    priceRange: {
      'avatar-studio': { min: 3000, max: 7000 },
      'full-body': { min: 8000, max: 18000 },
      greeting: { min: 800, max: 2500 },
    },
  },
  {
    id: 'elissa',
    name: 'Elissa',
    nameAr: 'إليسا',
    industry: 'music',
    verified: true,
    nationality: 'Lebanese',
    nationalityAr: 'لبنانية',
    languages: ['Arabic'],
    tags: ['Pop', 'Arabic', 'Romance'],
    tagsAr: ['بوب', 'عربي', 'رومانسي'],
    avatarColor: 'linear-gradient(135deg, #f472b6 0%, #db2777 100%)',
    initials: 'EL',
    image: '/celebs/elissa.svg',
    priceRange: {
      'avatar-studio': { min: 1200, max: 3000 },
      'full-body': { min: 3500, max: 8000 },
      greeting: { min: 350, max: 1000 },
    },
  },
  {
    id: 'srk',
    name: 'Shah Rukh Khan',
    nameAr: 'شاهروخ خان',
    industry: 'entertainment',
    verified: true,
    nationality: 'Indian',
    nationalityAr: 'هندي',
    languages: ['Hindi', 'English', 'Arabic'],
    tags: ['Bollywood', 'King of Bollywood', 'Icon'],
    tagsAr: ['بوليوود', 'ملك بوليوود', 'أيقونة'],
    avatarColor: 'linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)',
    initials: 'SK',
    image: '/celebs/srk.svg',
    priceRange: {
      'avatar-studio': { min: 3000, max: 7000 },
      'full-body': { min: 8000, max: 18000 },
      greeting: { min: 800, max: 2200 },
    },
  },
  {
    id: 'khaby',
    name: 'Khaby Lame',
    nameAr: 'خابي لام',
    industry: 'social-media',
    verified: true,
    nationality: 'Italian-Senegalese',
    nationalityAr: 'إيطالي سنغالي',
    languages: ['Italian', 'French', 'English'],
    tags: ['TikTok', 'Comedy', 'Viral'],
    tagsAr: ['تيك توك', 'كوميديا', 'فيروسي'],
    avatarColor: 'linear-gradient(135deg, #10b981 0%, #059669 100%)',
    initials: 'KL',
    image: '/celebs/khaby.svg',
    priceRange: {
      'avatar-studio': { min: 1500, max: 3500 },
      'full-body': { min: 4000, max: 9000 },
      greeting: { min: 400, max: 1200 },
    },
  },
  {
    id: 'tamer-hosny',
    name: 'Tamer Hosny',
    nameAr: 'تامر حسني',
    industry: 'music',
    verified: true,
    nationality: 'Egyptian',
    nationalityAr: 'مصري',
    languages: ['Arabic', 'English'],
    tags: ['Pop', 'Actor', 'Star of Generation'],
    tagsAr: ['بوب', 'ممثل', 'نجم الجيل'],
    avatarColor: 'linear-gradient(135deg, #f97316 0%, #dc2626 100%)',
    initials: 'TH',
    image: '/celebs/tamer-hosny.svg',
    priceRange: {
      'avatar-studio': { min: 1000, max: 2500 },
      'full-body': { min: 3000, max: 7000 },
      greeting: { min: 300, max: 900 },
    },
  },
  {
    id: 'gary-vee',
    name: 'Gary Vaynerchuk',
    nameAr: 'غاري فاينرتشوك',
    industry: 'business',
    verified: true,
    nationality: 'American',
    nationalityAr: 'أمريكي',
    languages: ['English'],
    tags: ['Entrepreneur', 'Marketing', 'NFT'],
    tagsAr: ['رياديّ', 'تسويق', 'NFT'],
    avatarColor: 'linear-gradient(135deg, #6366f1 0%, #4338ca 100%)',
    initials: 'GV',
    image: '/celebs/gary-vee.svg',
    priceRange: {
      'avatar-studio': { min: 1200, max: 3000 },
      'full-body': { min: 3500, max: 8000 },
      greeting: { min: 350, max: 1000 },
    },
  },
  {
    id: 'haifa',
    name: 'Haifa Wehbe',
    nameAr: 'هيفاء وهبي',
    industry: 'entertainment',
    verified: true,
    nationality: 'Lebanese',
    nationalityAr: 'لبنانية',
    languages: ['Arabic', 'English'],
    tags: ['Singer', 'Actress', 'Icon'],
    tagsAr: ['مغنية', 'ممثلة', 'أيقونة'],
    avatarColor: 'linear-gradient(135deg, #f59e0b 0%, #ef4444 100%)',
    initials: 'HW',
    image: '/celebs/haifa.svg',
    priceRange: {
      'avatar-studio': { min: 1500, max: 3500 },
      'full-body': { min: 4000, max: 9000 },
      greeting: { min: 400, max: 1200 },
    },
  },
  {
    id: 'federer',
    name: 'Roger Federer',
    nameAr: 'روجر فيدرر',
    industry: 'sports',
    verified: true,
    nationality: 'Swiss',
    nationalityAr: 'سويسري',
    languages: ['English', 'German', 'French', 'Italian'],
    tags: ['Tennis', 'GOAT', 'Global Icon'],
    tagsAr: ['تنس', 'أعظم لاعب', 'أيقونة عالمية'],
    avatarColor: 'linear-gradient(135deg, #0ea5e9 0%, #0369a1 100%)',
    initials: 'RF',
    image: '/celebs/federer.svg',
    priceRange: {
      'avatar-studio': { min: 3500, max: 7500 },
      'full-body': { min: 9000, max: 20000 },
      greeting: { min: 900, max: 2800 },
    },
  },
  {
    id: 'weeknd',
    name: 'The Weeknd',
    nameAr: 'ذا ويكند',
    industry: 'music',
    verified: true,
    nationality: 'Canadian',
    nationalityAr: 'كندي',
    languages: ['English'],
    tags: ['R&B', 'Pop', 'Billboards'],
    tagsAr: ['R&B', 'بوب', 'بيلبورد'],
    avatarColor: 'linear-gradient(135deg, #1e1b4b 0%, #7c3aed 100%)',
    initials: 'WK',
    image: '/celebs/weeknd.svg',
    priceRange: {
      'avatar-studio': { min: 4000, max: 8500 },
      'full-body': { min: 11000, max: 23000 },
      greeting: { min: 1000, max: 3200 },
    },
  },
  {
    id: 'messi',
    name: 'Lionel Messi',
    nameAr: 'ليونيل ميسي',
    industry: 'sports',
    verified: true,
    nationality: 'Argentine',
    nationalityAr: 'أرجنتيني',
    languages: ['Spanish', 'English'],
    tags: ['Football', 'GOAT', 'Inter Miami'],
    tagsAr: ['كرة القدم', 'أعظم لاعب', 'إنتر ميامي'],
    avatarColor: 'linear-gradient(135deg, #60a5fa 0%, #a78bfa 100%)',
    initials: 'LM',
    image: '/celebs/messi.svg',
    priceRange: {
      'avatar-studio': { min: 5000, max: 10000 },
      'full-body': { min: 14000, max: 30000 },
      greeting: { min: 1500, max: 4000 },
    },
  },
  {
    id: 'elon',
    name: 'Elon Musk',
    nameAr: 'إيلون ماسك',
    industry: 'business',
    verified: true,
    nationality: 'American-South African',
    nationalityAr: 'أمريكي جنوب أفريقي',
    languages: ['English'],
    tags: ['Tesla', 'SpaceX', 'X (Twitter)'],
    tagsAr: ['تسلا', 'سبيس إكس', 'إكس (تويتر)'],
    avatarColor: 'linear-gradient(135deg, #374151 0%, #111827 100%)',
    initials: 'EM',
    image: '/celebs/elon.svg',
    priceRange: {
      'avatar-studio': { min: 6000, max: 15000 },
      'full-body': { min: 18000, max: 40000 },
      greeting: { min: 2000, max: 6000 },
    },
  },
]

export const PRODUCT_TYPES: ProductType[] = [
  {
    id: 'greeting',
    name: 'Celebrity Greetings',
    nameAr: 'تحيات المشاهير',
    description: 'Personal occasions',
    descriptionAr: 'المناسبات الشخصية',
    detail:
      'Personalized celebrity messages for birthdays, weddings, graduations, and heartfelt appreciations.',
    detailAr:
      'رسائل مشاهير شخصية لأعياد الميلاد والأعراس والتخرج وعبارات الامتنان.',
    icon: '🎉',
    priceFrom: 149,
    duration: 'Delivery in 1–2 business days',
    durationAr: 'التسليم في غضون 1–2 يوم عمل',
    useCases: ['Birthdays', 'Weddings', 'Graduations', 'Corporate Appreciation'],
    useCasesAr: ['أعياد الميلاد', 'الأعراس', 'حفلات التخرج', 'التقدير المؤسسي'],
  },
  {
    id: 'avatar-studio',
    name: 'Short Product Ads',
    nameAr: 'إعلانات المنتجات القصيرة',
    description: 'Short celebrity Ad',
    descriptionAr: 'الرأس والكتفين',
    detail:
      'Hyper-realistic video avatars ideal for ads, product launches, and official announcements.',
    detailAr:
      'أفاتارات فيديو فائقة الواقعية مثالية للإعلانات وإطلاق المنتجات والإعلانات الرسمية.',
    icon: '🎬',
    priceFrom: 299,
    duration: 'Delivery in 3–5 business days',
    durationAr: 'التسليم في غضون 3–5 أيام عمل',
    useCases: ['Brand Ads', 'Product Launches', 'Corporate Announcements', 'Social Media Posts'],
    useCasesAr: ['إعلانات العلامة التجارية', 'إطلاق المنتجات', 'الإعلانات الشركاتية', 'منشورات وسائل التواصل الاجتماعي'],
  },
  {
    id: 'full-body',
    name: 'Full-Body Digital Twin',
    nameAr: 'التوأم الرقمي للجسم الكامل',
    description: 'Full body celebrity Ad',
    descriptionAr: 'الجسم الكامل + التقاط الحركة',
    detail:
      'Complete digital twin with natural body motion for large-scale campaigns and immersive experiences.',
    detailAr:
      'توأم رقمي كامل مع حركة جسمية طبيعية للحملات الكبيرة والتجارب الغامرة.',
    icon: '🧬',
    priceFrom: 899,
    duration: 'Delivery in 7–14 business days',
    durationAr: 'التسليم في غضون 7–14 يوم عمل',
    useCases: ['TV Commercials', 'Event Displays', 'Campaign Videos', 'Immersive Brand Experiences'],
    useCasesAr: ['إعلانات تلفزيونية', 'عروض الفعاليات', 'مقاطع فيديو الحملات', 'تجارب العلامة التجارية الغامرة'],
  },
]

export const TEMPLATES: Template[] = [
  // Avatar Studio Templates
  {
    id: 'brand-launch',
    purpose: 'Brand Launch',
    purposeAr: 'إطلاق العلامة التجارية',
    name: 'Epic Launch Reveal',
    nameAr: 'الكشف الملحمي للإطلاق',
    description: 'A powerful announcement format with a strong opening hook and brand CTA.',
    descriptionAr: 'تنسيق إعلان قوي مع خطاف افتتاحي قوي ودعوة إلى العمل للعلامة التجارية.',
    sampleScript:
      "I'm [Celebrity Name], and I'm thrilled to introduce [Brand Name] — the future of [Industry]. Get ready to experience something extraordinary.",
    sampleScriptAr:
      'أنا [اسم المشهور]، ويسعدني تقديم [اسم العلامة التجارية] — مستقبل [الصناعة]. استعد لتجربة شيء استثنائي.',
    productTypes: ['avatar-studio', 'full-body'],
    duration: '30s',
    tags: ['Launch', 'Brand', 'Announcement'],
  },
  {
    id: 'product-ad',
    purpose: 'Product Advertisement',
    purposeAr: 'إعلان المنتج',
    name: 'Product Hero Ad',
    nameAr: 'إعلان بطل المنتج',
    description: 'Highlight the key features of your product with celebrity endorsement.',
    descriptionAr: 'سلّط الضوء على المميزات الرئيسية لمنتجك مع تأييد المشاهير.',
    sampleScript:
      "I've tried countless products, but [Product Name] stands out. Here's why I choose it every single day.",
    sampleScriptAr:
      'جربت منتجات لا حصر لها، لكن [اسم المنتج] يبرز من بينها. إليك سبب اختياري له كل يوم.',
    productTypes: ['avatar-studio', 'full-body'],
    duration: '30s',
    tags: ['Product', 'Ad', 'Endorsement'],
  },
  {
    id: 'corporate-announcement',
    purpose: 'Corporate Announcement',
    purposeAr: 'إعلان مؤسسي',
    name: 'Official Statement',
    nameAr: 'البيان الرسمي',
    description: 'A formal, authoritative message for company milestones or important news.',
    descriptionAr: 'رسالة رسمية وموثوقة لإنجازات الشركة أو الأخبار المهمة.',
    sampleScript:
      'On behalf of [Company Name], I am proud to announce [News]. This marks a significant milestone in our journey.',
    sampleScriptAr:
      'نيابةً عن [اسم الشركة]، يسعدني الإعلان عن [الخبر]. يُمثّل هذا منعطفاً مهماً في مسيرتنا.',
    productTypes: ['avatar-studio'],
    duration: '60s',
    tags: ['Corporate', 'Formal', 'News'],
  },
  // Greeting Templates
  {
    id: 'birthday-wish',
    purpose: 'Birthday',
    purposeAr: 'عيد ميلاد',
    name: 'Birthday Surprise',
    nameAr: 'مفاجأة عيد الميلاد',
    description: 'A warm, celebratory birthday message personalized with the recipient\'s name.',
    descriptionAr: 'رسالة عيد ميلاد دافئة وفرحة مخصصة باسم المستلم.',
    sampleScript:
      "Hey [Name]! It's [Celebrity Name] wishing you the most incredible birthday. You deserve nothing but the best today and every day!",
    sampleScriptAr:
      'مرحباً [الاسم]! أنا [اسم المشهور] أتمنى لك عيد ميلاد رائع. تستحق الأفضل دائماً!',
    productTypes: ['greeting', 'avatar-studio'],
    duration: '15s',
    tags: ['Birthday', 'Personal', 'Celebration'],
  },
  {
    id: 'wedding-greeting',
    purpose: 'Wedding',
    purposeAr: 'زفاف',
    name: 'Wedding Blessing',
    nameAr: 'تهنئة الزفاف',
    description: 'An elegant and heartfelt wedding congratulation message.',
    descriptionAr: 'رسالة تهنئة زفاف أنيقة ومؤثرة.',
    sampleScript:
      '[Name1] and [Name2], congratulations on this beautiful day! May your love story be as legendary as the greatest love stories ever told.',
    sampleScriptAr:
      '[الاسم الأول] و[الاسم الثاني]، مبروك في هذا اليوم الجميل! أتمنى أن تكون قصة حبكما رائعة.',
    productTypes: ['greeting', 'avatar-studio'],
    duration: '30s',
    tags: ['Wedding', 'Love', 'Celebration'],
  },
  {
    id: 'graduation',
    purpose: 'Graduation',
    purposeAr: 'تخرج',
    name: 'Graduation Motivation',
    nameAr: 'تحفيز التخرج',
    description: 'An inspiring graduation message to celebrate academic achievement.',
    descriptionAr: 'رسالة تخرج ملهمة للاحتفال بالإنجاز الأكاديمي.',
    sampleScript:
      "Congratulations, [Name]! You've worked so hard for this moment. The world is yours to conquer — go make it happen!",
    sampleScriptAr:
      'مبروك [الاسم]! عملت بجد لهذه اللحظة. العالم في انتظارك — اذهب واجعله حقيقة!',
    productTypes: ['greeting', 'avatar-studio'],
    duration: '30s',
    tags: ['Graduation', 'Academic', 'Achievement'],
  },
  {
    id: 'appreciation',
    purpose: 'Appreciation',
    purposeAr: 'تقدير',
    name: 'Team Appreciation',
    nameAr: 'تقدير الفريق',
    description: 'Recognize outstanding performance with a celebrity thank-you message.',
    descriptionAr: 'اعترف بالأداء المتميز برسالة شكر من مشهور.',
    sampleScript:
      '[Name], your dedication and hard work truly make a difference. On behalf of [Company], thank you for everything you do!',
    sampleScriptAr:
      '[الاسم]، تفانيك وعملك الجاد يحدثان فرقاً حقيقياً. نيابةً عن [الشركة]، شكراً لك على كل ما تفعله!',
    productTypes: ['greeting', 'avatar-studio'],
    duration: '30s',
    tags: ['Appreciation', 'Corporate', 'Thank You'],
  },
  // Full-Body Templates
  {
    id: 'campaign-video',
    purpose: 'Campaign',
    purposeAr: 'حملة',
    name: 'Campaign Flagship',
    nameAr: 'الحملة الرئيسية',
    description: 'A full-body dynamic video for large-scale brand campaigns.',
    descriptionAr: 'فيديو ديناميكي بالجسم الكامل للحملات الكبيرة للعلامة التجارية.',
    sampleScript:
      "This is [Brand Name]'s most ambitious campaign yet. I believe in this vision, and I want you to be part of it.",
    sampleScriptAr:
      'هذه أطموح حملة [اسم العلامة التجارية] حتى الآن. أؤمن بهذه الرؤية، وأريدك أن تكون جزءاً منها.',
    productTypes: ['full-body'],
    duration: '60s',
    tags: ['Campaign', 'Brand', 'Full-Body'],
  },
  {
    id: 'event-invite',
    purpose: 'Event',
    purposeAr: 'فعالية',
    name: 'VIP Event Invitation',
    nameAr: 'دعوة فعالية VIP',
    description: 'An exclusive event invitation delivered by a celebrity.',
    descriptionAr: 'دعوة حصرية لفعالية يقدمها مشهور.',
    sampleScript:
      "You're exclusively invited to [Event Name]. Join us on [Date] for an evening you won't forget. I'll be there — will you?",
    sampleScriptAr:
      'أنت مدعو حصرياً إلى [اسم الفعالية]. انضم إلينا في [التاريخ] لأمسية لن تنساها. سأكون هناك — هل ستحضر؟',
    productTypes: ['full-body', 'avatar-studio'],
    duration: '30s',
    tags: ['Event', 'Invitation', 'VIP'],
  },
]

export const INDUSTRY_LABELS: Record<string, { en: string; ar: string }> = {
  all: { en: 'All', ar: 'الكل' },
  entertainment: { en: 'Entertainment', ar: 'ترفيه' },
  sports: { en: 'Sports', ar: 'رياضة' },
  music: { en: 'Music', ar: 'موسيقى' },
  business: { en: 'Business', ar: 'أعمال' },
  'social-media': { en: 'Social Media', ar: 'وسائل التواصل' },
  'tv-film': { en: 'TV & Film', ar: 'تلفزيون وسينما' },
}

export const TONES = [
  { id: 'professional', en: 'Professional', ar: 'احترافي' },
  { id: 'casual', en: 'Casual', ar: 'عادي' },
  { id: 'energetic', en: 'Energetic', ar: 'نشيط' },
  { id: 'warm', en: 'Warm & Friendly', ar: 'دافئ وودود' },
  { id: 'inspirational', en: 'Inspirational', ar: 'ملهم' },
  { id: 'humorous', en: 'Humorous', ar: 'فكاهي' },
]

export const CHANNELS = [
  { id: 'social-media', en: 'Social Media', ar: 'وسائل التواصل', icon: '📱' },
  { id: 'tv-ad', en: 'TV Advertisement', ar: 'إعلان تلفزيوني', icon: '📺' },
  { id: 'website', en: 'Website / Landing Page', ar: 'الموقع الإلكتروني', icon: '🌐' },
  { id: 'email', en: 'Email Campaign', ar: 'حملة بريدية', icon: '📧' },
  { id: 'event', en: 'Live Event', ar: 'فعالية مباشرة', icon: '🎪' },
  { id: 'youtube', en: 'YouTube / Streaming', ar: 'يوتيوب / بث', icon: '▶️' },
]

export const DURATIONS = [
  { id: '10s', en: '10 sec', ar: '10 ثوانٍ' },
  { id: '15s', en: '15 sec', ar: '15 ثانية' },
  { id: '30s', en: '30 sec', ar: '30 ثانية' },
  { id: '60s', en: '60 sec', ar: '60 ثانية' },
]

export const ASPECT_RATIOS = [
  { id: '16:9', label: '16:9', hint: 'YouTube / Widescreen', hintAr: 'يوتيوب / عريض' },
  { id: '9:16', label: '9:16', hint: 'Social Media / Reels', hintAr: 'سوشيال ميديا'  },
]

export const RESOLUTIONS = [
  { id: '720p',  label: '720p',  hint: 'HD',       hintAr: 'عالي الدقة'   },
  { id: '1080p', label: '1080p', hint: 'Full HD',  hintAr: 'فائق الدقة'   },
  { id: '4K',    label: '4K',    hint: 'Ultra HD', hintAr: 'فائق الجودة'  },
]

export const MOCK_ORDERS = [
  {
    id: 'TWN-2024-001',
    status: 'delivered',
    celebrity: 'Mohamed Salah',
    productType: 'Avatar Studio',
    purpose: 'Brand Launch',
    createdAt: '2024-11-15',
    estimatedPrice: 4200,
    currency: 'USD',
  },
  {
    id: 'TWN-2024-002',
    status: 'in-progress',
    celebrity: 'Amr Diab',
    productType: 'Celebrity Greetings',
    purpose: 'Birthday',
    createdAt: '2024-12-02',
    estimatedPrice: 800,
    currency: 'USD',
  },
  {
    id: 'TWN-2024-003',
    status: 'review',
    celebrity: 'Neymar Jr.',
    productType: 'Full-Body Digital Twin',
    purpose: 'Campaign',
    createdAt: '2024-12-10',
    estimatedPrice: 15000,
    currency: 'USD',
  },
  {
    id: 'TWN-2024-004',
    status: 'delivered',
    celebrity: 'Cristiano Ronaldo',
    productType: 'Celebrity Greetings',
    purpose: 'Product Launch',
    createdAt: '2024-12-01',
    estimatedPrice: 1200,
    currency: 'USD',
  },
  {
    id: 'TWN-2024-005',
    status: 'pending',
    celebrity: 'Haifa Wehbe',
    productType: 'Celebrity Greetings',
    purpose: 'Event Invite',
    createdAt: '2024-12-12',
    estimatedPrice: 600,
    currency: 'USD',
  },
]
